kafka.bootstrap.servers=kafka:9092
kafka.topic=mock-data
kafka.group.id=flink-lab3-consumer

jdbc.url=jdbc:postgresql://postgres:5555/lab3
jdbc.user=student
jdbc.password=student

flink.parallelism=1
flink.checkpoint.interval.ms=15000

jdbc.batch.size=1
jdbc.batch.interval.ms=1000

# Detailed Flink processing logs
flink.log.every.n.messages=500
flink.log.preview.length=220
